version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id

        loaded_at_field: "CAST( date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }

        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: products_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by a customer to purchase the product; revenue = quantity * selling price
          - name: quantity
            description: quantity of purchased products for a given customer
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: Primary key
            tests:
              - unique
              - not_null 
          - name: purchase_price
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: shipping data of Greenweez orders
        columns:
          - name: orders_id
            description: Primary key 
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays to cover shipping fees
          - name: logcost
            description: the cost associated in preparing the parcel in the distribuition centre/warehouse
          - name: shipping_cost
            description: cost incurred by Greenweez for orders to be shipped to the carrier/logistics provider
          